https://github.com/GidroN/MuzApp/issues/6 Test diplom2
GidroN/MuzApp pull request #7
Opened 2024-05-17 13:52 UTC by MrGoosee

https://github.com/GidroN/MuzApp/issues/6

2024-05-17 15:02 UTC, GidroN requested changes

2024-05-17 15:02 UTC, GidroN commented on events.py
> +def carts(e):
Сделай название на английском. Никаких транскриптов. В данном случае подойдёт - **maps**

2024-05-17 16:04 UTC, GidroN commented on views.py
> +#testtt2
```suggestion
#testtt3
```

2024-05-19 11:06 UTC, MrGoosee commented on events.py
> +def carts(e):
fc

2024-05-19 21:00 UTC, MrGoosee commented
Даааааа

2024-05-19 21:23 UTC, GidroN requested changes
Окей годно. Только тестовый файлик добавь в гитигноре.

2024-05-19 21:33 UTC, GidroN requested changes
Годно, только добавь тестовый файл в гитигноре

2024-05-20 06:26 UTC, GidroN requested changes
В гитигноре тестовый файлик не добавил

2024-05-20 06:30 UTC, GidroN approved these changes
Approved

2024-05-20 06:36 UTC, merged