Diplom
GidroN/MuzApp pull request #9
Opened 2024-06-04 16:03 UTC by MrGoosee

Тошаааааааааааааа

2024-06-04 20:24 UTC, GidroN requested changes

2024-06-04 20:24 UTC, GidroN commented on views.py
> +                ],
Много повторяющегося кода. Лучше вынести в отдельную функцию или переменную. Тоже самое с другими вьюхами.

2024-06-04 20:24 UTC, GidroN commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
А event у тебя разве не динамический будет? Как например ```/mus/:id/```

2024-06-04 20:24 UTC, GidroN commented on events.py
> +    2: '/events/',
Routes тоже лучше вынести в отдельный файлик, а лучше даже класс с константами `IntEnum`

2024-06-08 08:11 UTC, MrGoosee commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
нет так как там будет список так же как и на главной страничке

2024-06-08 08:15 UTC, MrGoosee commented on events.py
> +    2: '/events/',
готово

2024-06-08 10:54 UTC, GidroN commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
А на каждое событие можно будет перейти?

2024-06-09 07:15 UTC, MrGoosee commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
да. Вот там как раз и будет динамическая. Всё как с музеями.

2024-06-10 17:10 UTC, BelozerSavely commented
ВПЕРЕД, ДАВАЙ,ДАВАЙ, УРА, ДАВАЙ ЗА ДИПЛОМ, УРААА, УРААА,УРААА!!!!))0)❤❤❤😍😍👀👀👀👀👏👏✌✌✌🤞🤞🤞💕ZZZZZZZZZ VVVV VVVVVV ZOV ZOV ZOV SVO SVO ZVO OZV!!!!

2024-06-11 14:17 UTC, GidroN commented on events.py
> +#     ),
Удали ненужные комменты.

2024-06-11 14:20 UTC, GidroN commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
В таком случае нужно будет как саму страницу с событиями сделать, так и динамическую страничку для каждого события.
```suggestion
    path(url='/events/', clear=False, view=eventViews),
    path(url='/events/:id', clear=False, view=eventInfoView)```

2024-06-11 14:28 UTC, GidroN commented on routesevents.py
> +}
Назвои лучше этот файлик как `constants.py`

2024-06-11 14:33 UTC, GidroN commented on routesevents.py
> +ROUTES = {
```suggestion
ROUTES
```

2024-06-11 14:39 UTC, GidroN commented
Также еще необходимо разделить вьюхи на несколько файликов, а то получается загромождение одного файла.
Создай папочку views и уже внутри каждую вьюху сделай отдельным файликом. Так наверное даже лучше и удобнее будет.

2024-06-11 14:40 UTC, GidroN commented on views.py
> +                ],
А вообще лучше сделай отдельную папочку с вьюхами.

2024-06-12 10:27 UTC, MrGoosee commented on routes.py
> +    path(url='/events/', clear=False, view=eventViews),
а зачем её делать денамической? Если мне надо будет другую стр делать денамической.

2024-06-12 10:28 UTC, MrGoosee commented on events.py
> +#     ),
Это пока надо. Не трожай.

2024-06-12 10:31 UTC, MrGoosee commented on routesevents.py
> +ROUTES = {
Ну ок

2024-06-12 14:56 UTC, merged